const products = [
  {
    _id: "1",
    name: "Airpods Wireless Bluetooth Headphones",
    image: "/images/airpods.jpg",
    description:
      "Bluetooth technology lets you connect it with compatible devices wirelessly. High-Quality ACC audio offers immersive listening experience. Built-in microphone allows you to take calls while working.",
    brand: "Apple",
    category: "Electronics",
    price: 89.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: "2",
    name: "Alexa Voice Assistant",
    image: "/images/alexa.jpg",
    description:
      "Smart speaker with Alexa voice assistant. Control your smart home, play music, and get information hands-free.",
    brand: "Amazon",
    category: "Electronics",
    price: 49.99,
    countInStock: 7,
    rating: 4.0,
    numReviews: 8,
  },
  {
    _id: "3",
    name: "Canon EOS DSLR Camera",
    image: "/images/camera.jpg",
    description:
      "Capture stunning photos and videos with this high-resolution DSLR camera. Features fast autofocus and versatile lens compatibility.",
    brand: "Canon",
    category: "Electronics",
    price: 599.99,
    countInStock: 5,
    rating: 4.8,
    numReviews: 15,
  },
  {
    _id: "4",
    name: "Logitech Wireless Mouse",
    image: "/images/mouse.jpg",
    description:
      "Ergonomic wireless mouse with long battery life and precise tracking. Perfect for office and gaming use.",
    brand: "Logitech",
    category: "Electronics",
    price: 19.99,
    countInStock: 25,
    rating: 4.3,
    numReviews: 22,
  },
  {
    _id: "5",
    name: "iPhone 14 Pro",
    image: "/images/phone.jpg",
    description:
      "Latest Apple iPhone with advanced camera system, powerful processor, and stunning display.",
    brand: "Apple",
    category: "Electronics",
    price: 999.99,
    countInStock: 8,
    rating: 4.7,
    numReviews: 30,
  },
  {
    _id: "6",
    name: "Sony PlayStation 5",
    image: "/images/playstation.jpg",
    description:
      "Next-generation gaming console with ultra-fast SSD and immersive graphics. Play the latest games in stunning detail.",
    brand: "Sony",
    category: "Electronics",
    price: 499.99,
    countInStock: 4,
    rating: 4.9,
    numReviews: 40,
  },
  {
    _id: "7",
    name: "Sample Product",
    image: "/images/sample.jpg",
    description:
      "This is a sample product for demonstration purposes. Replace with real product details.",
    brand: "SampleBrand",
    category: "SampleCategory",
    price: 0.99,
    countInStock: 100,
    rating: 3.0,
    numReviews: 1,
  },
  {
    _id: "8",
    name: "Samsung 27-inch 4K Monitor",
    image: "/images/screens.jpg",
    description:
      "Ultra HD 4K monitor with vibrant colors and fast refresh rate. Ideal for work and entertainment.",
    brand: "Samsung",
    category: "Electronics",
    price: 329.99,
    countInStock: 12,
    rating: 4.6,
    numReviews: 18,
  },
];

export default products;
